# Generated by Django 2.2.5 on 2020-12-15 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card_info', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='card_info.CardInfo')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_profile.UserProfile')),
            ],
        ),
    ]
