# Generated by Django 2.2.5 on 2020-12-15 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_color', models.CharField(choices=[('white', 'white'), ('blue', 'blue'), ('red', 'red'), ('green', 'green'), ('black', 'black')], max_length=5)),
                ('card_id', models.ForeignKey(blank=True, default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='card_info.CardInfo')),
            ],
        ),
    ]
