# Generated by Django 2.2.5 on 2020-12-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_color', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardcolor',
            name='card_id',
        ),
    ]
