# Generated by Django 2.2.5 on 2020-12-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('author', models.CharField(blank=True, max_length=128)),
                ('image_url', models.CharField(blank=True, max_length=128)),
                ('expansion', models.CharField(blank=True, max_length=128)),
                ('type', models.CharField(blank=True, max_length=128)),
                ('lore_message', models.CharField(blank=True, max_length=128, null=True)),
                ('lore_author', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
