# Generated by Django 2.2.5 on 2020-12-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_color', '0002_remove_cardcolor_card_id'),
        ('card_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinfo',
            name='colors',
            field=models.ManyToManyField(to='card_color.CardColor'),
        ),
    ]
