# Generated by Django 2.2.5 on 2020-12-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_info', '0002_cardinfo_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardinfo',
            name='image_url',
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='card_images'),
        ),
    ]
