# Generated by Django 2.2.5 on 2020-12-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_info', '0003_auto_20201216_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='author',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='expansion',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='lore_author',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='lore_message',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='type',
            field=models.CharField(max_length=128),
        ),
    ]
